import enum


class DispositionClassification(enum.Enum):
    CONVICTION = "CONVICTION"
    NON_CONVICTION = "NON_CONVICTION"
    NOT_ENOUGH_INFORMATION = "NOT_ENOUGH_INFORMATION"
    PENDING = "PENDING"
